- name: copy prometheus configuration
  ansible.builtin.template:
    src: "{{item}}.yml"
    dest: /opt/prometheus/{{item}}.yml
  loop:
    - prometheus
    - alerts

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Wait for promethues is started or not
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15

