- name: Create Application User
  ansible.builtin.user:
    name: "{{app_user}}"

- name: Clean Old App content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory
#- name: Download App Content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

- name: Download App Content
  ansible.builtin.unarchive:
    src: http://172.31.87.83:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes

